version: '2'
services:
    esat_app-app:
        image: esat_app
        external_links:
            - esat_app-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/esat_app?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    esat_app-mysql:
        extends:
            file: mysql.yml
            service: esat_app-mysql
